### ISSUE TITLE
Till 197 epoches =>Epoches 197, learning rate = 0.00000002, after that following error

### ISSUE THREAD

**Issue by Jayku88** [wycloveinfall/MSMDFF-NET#3]
Traceback (most recent call last):
  File "train.py", line 277, in <module>
    batch_loss_n, pred = solver.optimize(index+1,epoch)
  File "/home/jayakumar/MSMDFF-NET-main/utils/frame_work_general.py", line 113, in optimize
    self.lr_current = self.scheduler(self.optimizer, i, epoch,debuge=False)
  File "/home/jayakumar/MSMDFF-NET-main/utils/learnlingrate_methods/lr_scheduler.py", line 61, in __call__
    assert lr >= 0
AssertionError
Exception in thread Thread-405:
Traceback (most recent call last):
  File "/home/jayakumar/anaconda3/envs/torch1.9sta/lib/python3.8/threading.py", line 932, in _bootstrap_inner

**Comment by wycloveinfall** [comment]
你好：
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 请问你遇到了设呢么问题吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wycloveinfall/MSMDFF-NET"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月27日(星期四) 中午11:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wycloveinfall/MSMDFF-NET] Till 197 epoches =&gt;Epoches 197, learning rate = 0.00000002, after that following error (Issue #3)





 
Traceback (most recent call last):
 File "train.py", line 277, in 
 batch_loss_n, pred = solver.optimize(index+1,epoch)
 File "/home/jayakumar/MSMDFF-NET-main/utils/frame_work_general.py", line 113, in optimize
 self.lr_current = self.scheduler(self.optimizer, i, epoch,debuge=False)
 File "/home/jayakumar/MSMDFF-NET-main/utils/learnlingrate_methods/lr_scheduler.py", line 61, in call
 assert lr &gt;= 0
 AssertionError
 Exception in thread Thread-405:
 Traceback (most recent call last):
 File "/home/jayakumar/anaconda3/envs/torch1.9sta/lib/python3.8/threading.py", line 932, in _bootstrap_inner

**Comment by wycloveinfall** [comment]
这个问题可以参考，之前我的回复“https://github.com/wycloveinfall/MSMDFF-NET/issues/1”

**Comment by Jayku88** [comment]
是的。当然。知道了

**Comment by LPeng625** [comment]
> 是的。当然。知道了

https://github.com/wycloveinfall/MSMDFF-NET/issues/4

Hello, I am very confused about this question, can you help me to answer it? thank you！
